import '../classesanddata/catigoris.dart';
import '../classesanddata/catigory_detail_class.dart';

final Catigory1 = 
Catigory(
  id:"c1",
  title:"Burger",
  image:"images/logo2.jpg");

final Catigory2 = 
Catigory(
  id:"c2",
  title:"Shawarma",
  image:"images/شاورما.jpg");

final Catigory3 = 
Catigory(
  id:"c3",
  title:"Pasta",
  image:"images/pasta.jpeg");

final Catigory4 = 
Catigory(
  id:"c4",
  title:"Pizza",
  image:"images/pizza.jpeg");

final Catigory5 = 
Catigory(
  id:"c5",
  title:"Fish",
  image:"images/fish.jpeg");

final Catigory6 = 
Catigory(
  id:"c6",
  title:"Korean&Chiness",
  image:"images/korean&chiness.jpg");

final Catigory7 = 
Catigory(
  id:"c7",
  title:"Meels",
  image:"images/وجبات.jpeg");

final Catigory8 = 
Catigory(
  id:"c8",
  title:"Crepe",
  image:"images/كريب.jpeg");

final Catigory9 = 
Catigory(
  id:"c9",
  title:"Sweets",
  image:"images/sweet.jpeg");

final Catigory10 = 
Catigory(
  id:"c10",
  title:"Cold Drinks",
  image:"images/drinks.jpeg");

final Catigory11 = 
Catigory(
  id:"c11",
  title:"Hot Drinks",
  image:"images/hotdrinks1.jpeg");


final List<Catigory> catigoryList = [
  Catigory1,
  Catigory2,
  Catigory3,
  Catigory4,
  Catigory5,
  Catigory6,
  Catigory7,
  Catigory8,
  Catigory9,
  Catigory10,
  Catigory11,
];


final List<CatigoryDetailClass> catigories_data = [
  CatigoryDetailClass(
    id: '1',
    catigory: "c1",
    image: 'images/burger1.jpeg',
    title: 'Classic Burger',
    ingredients: 'Beef Patty, Lettuce, Tomato, Onion, Pickles, Ketchup, Mayo, Bun',
    size: Sizes.medium,
    extra: 'Cheese',
    price: '\$8.99',
    calories: 650,
    rating: 4.5,
    reviews: ['Tasty and classic!', 'Great value for money.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Beef', 'Classic'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '2',
    image: 'images/burger2.jpeg',
    catigory: "c1",
    title: 'Cheeseburger',
    ingredients: 'Beef Patty, Cheese, Lettuce, Tomato, Onion, Pickles, Ketchup, Mayo, Bun',
    size: Sizes.medium,
    extra: 'Double Cheese',
    price: '\$9.99',
    calories: 700,
    rating: 4.8,
    reviews: ['Perfect cheeseburger!', 'Cheese lovers will enjoy it.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Beef', 'Cheese'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '3',
    catigory: "c1",
    image: 'images/burger3.jpeg',
    title: 'Veggie Burger',
    ingredients: 'Veggie Patty, Lettuce, Tomato, Onion, Avocado, Vegan Mayo, Whole Wheat Bun',
    size: Sizes.medium,
    extra: 'Guacamole',
    price: '\$7.99',
    calories: 550,
    rating: 4.3,
    reviews: ['Delicious and healthy!', 'A great option for vegetarians.'],
    allergens: ['Gluten'],
    tags: ['Vegetarian', 'Vegan'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '4',
    image: 'images/burger4.jpeg',
    catigory: "c1",
    title: 'Bacon Burger',
    ingredients: 'Beef Patty, Bacon, Cheese, Lettuce, Tomato, Onion, BBQ Sauce, Bun',
    size: Sizes.large,
    extra: 'Extra Bacon',
    price: '\$11.99',
    calories: 850,
    rating: 4.7,
    reviews: ['Bacon makes everything better!', 'Hearty and satisfying.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Beef', 'Bacon'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '5',
    image: 'images/burger5.jpeg',
    catigory: "c1",
    title: 'Chicken Burger',
    ingredients: 'Grilled Chicken Breast, Lettuce, Tomato, Onion, Mayo, Bun',
    size: Sizes.medium,
    extra: 'Spicy Sauce',
    price: '\$8.49',
    calories: 600,
    rating: 4.6,
    reviews: ['Juicy and flavorful!', 'A great alternative to beef.'],
    allergens: ['Gluten'],
    tags: ['Chicken'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '6',
    catigory: "c1",
    image: 'images/burger6.jpeg',
    title: 'Portobello Mushroom Burger',
    ingredients: 'Grilled Portobello Mushroom, Lettuce, Tomato, Onion, Pesto Sauce, Bun',
    size: Sizes.medium,
    extra: 'Vegan Cheese',
    price: '\$9.49',
    calories: 500,
    rating: 4.4,
    reviews: ['Healthy and delicious!', 'A good vegan option.'],
    allergens: ['Gluten', 'Nuts (Pesto)'],
    tags: ['Vegan', 'Mushroom'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '7',
    catigory: "c1",
    image: 'images/burger7.jpg',
    title: 'Double Burger',
    ingredients: 'Two Beef Patties, Cheese, Lettuce, Tomato, Onion, Pickles, Ketchup, Mayo, Bun',
    size: Sizes.large,
    extra: 'Double Cheese',
    price: '\$12.99',
    calories: 950,
    rating: 4.9,
    reviews: ['Big and filling!', 'For the true burger lover.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Beef', 'Double'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 15),
  ),

  CatigoryDetailClass(
    id: '8',
    catigory: "c2",
    image: 'images/shawerma1.jpeg',
    title: 'Chicken Shawarma',
    ingredients: 'Chicken, Garlic Sauce, Pickles, Tomato, Onion, Pita Bread',
    size: Sizes.medium,
    extra: 'Extra Garlic Sauce',
    price: '\$6.99',
    calories: 500,
    rating: 4.7,
    reviews: ['Tender chicken and flavorful!', 'The garlic sauce is amazing.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Chicken', 'Classic'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '9',
    catigory: "c2",
    image: 'images/shawerma2.jpeg',
    title: 'Beef Shawarma',
    ingredients: 'Beef, Tahini Sauce, Pickles, Tomato, Onion, Pita Bread',
    size: Sizes.medium,
    extra: 'Spicy Tahini',
    price: '\$7.49',
    calories: 600,
    rating: 4.8,
    reviews: ['Rich and savory!', 'Perfectly spiced beef.'],
    allergens: ['Gluten', 'Nuts (Tahini)'],
    tags: ['Beef', 'Spicy'],
    preparationTime: Duration(minutes: 25),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '10',
    catigory: "c2",
    image: 'images/shawerma3.jpeg',
    title: 'Lamb Shawarma',
    ingredients: 'Lamb, Yogurt Sauce, Pickles, Tomato, Onion, Pita Bread',
    size: Sizes.medium,
    extra: 'Mint Yogurt Sauce',
    price: '\$8.99',
    calories: 650,
    rating: 4.6,
    reviews: ['Tender lamb and fresh ingredients!', 'A great twist on the classic.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Lamb', 'Classic'],
    preparationTime: Duration(minutes: 25),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '11',
    catigory: "c2",
    image: 'images/shawarma4.jpg',
    title: 'Veggie Shawarma',
    ingredients: 'Grilled Vegetables, Hummus, Pickles, Tomato, Onion, Pita Bread',
    size: Sizes.medium,
    extra: 'Extra Hummus',
    price: '\$6.49',
    calories: 450,
    rating: 4.5,
    reviews: ['Great for vegetarians!', 'The hummus adds a nice touch.'],
    allergens: ['Gluten', 'Sesame (Hummus)'],
    tags: ['Vegetarian', 'Healthy'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '12',
    catigory: "c2",
    image: 'images/shawarma5.jpg',
    title: 'Turkey Shawarma',
    ingredients: 'Turkey, Garlic Sauce, Pickles, Tomato, Onion, Pita Bread',
    size: Sizes.medium,
    extra: 'Spicy Garlic Sauce',
    price: '\$7.29',
    calories: 550,
    rating: 4.4,
    reviews: ['Lean and flavorful!', 'The spicy sauce is great.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Turkey', 'Spicy'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '13',
    catigory: "c2",
    image: 'images/shawerma6.jpeg',
    title: 'Falafel Shawarma',
    ingredients: 'Falafel, Tahini Sauce, Pickles, Tomato, Onion, Pita Bread',
    size: Sizes.medium,
    extra: 'Extra Tahini Sauce',
    price: '\$6.99',
    calories: 500,
    rating: 4.7,
    reviews: ['Crunchy falafel and tasty!', 'Tahini is a must-have.'],
    allergens: ['Gluten', 'Sesame (Tahini)'],
    tags: ['Vegetarian', 'Middle Eastern'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '14',
    catigory: "c2",
    image: 'images/shawarma7.jpg',
    title: 'Shawarma Platter',
    ingredients: 'Choice of Shawarma Meat, Rice, Hummus, Pickles, Salad',
    size: Sizes.large,
    extra: 'Extra Hummus and Rice',
    price: '\$12.99',
    calories: 800,
    rating: 4.9,
    reviews: ['A complete meal!', 'Generous portions and great flavors.'],
    allergens: ['Gluten', 'Dairy', 'Sesame (Hummus)'],
    tags: ['Mixed', 'Platter'],
    preparationTime: Duration(minutes: 30),
    cookingTime: Duration(minutes: 20),
  ),

  CatigoryDetailClass(
    id: '15',
    catigory: "c3",
    image: 'images/pasta1.jpeg',
    title: 'Spaghetti Bolognese',
    ingredients: 'Spaghetti, Ground Beef, Tomato Sauce, Onion, Garlic, Carrot, Celery, Parmesan Cheese',
    size: Sizes.medium,
    extra: 'Extra Parmesan Cheese',
    price: '\$12.99',
    calories: 800,
    rating: 4.8,
    reviews: ['Rich and flavorful!', 'Perfectly cooked pasta.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Beef', 'Italian'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 30),
  ),
  CatigoryDetailClass(
    id: '16',
    catigory: "c3",
    image: 'images/pasta2.jpeg',
    title: 'Fettuccine Alfredo',
    ingredients: 'Fettuccine, Cream, Butter, Parmesan Cheese, Garlic, Black Pepper',
    size: Sizes.medium,
    extra: 'Extra Cream Sauce',
    price: '\$13.49',
    calories: 900,
    rating: 4.7,
    reviews: ['Creamy and delicious!', 'A classic favorite.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Creamy', 'Italian'],
    preparationTime: Duration(minutes: 10),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '17',
    catigory: "c3",
    image: 'images/pasta3.jpeg',
    title: 'Lasagna',
    ingredients: 'Lasagna Noodles, Ground Beef, Tomato Sauce, Ricotta Cheese, Mozzarella Cheese, Parmesan Cheese, Garlic, Onion',
    size: Sizes.large,
    extra: 'Extra Mozzarella Cheese',
    price: '\$14.99',
    calories: 1000,
    rating: 4.9,
    reviews: ['Hearty and satisfying!', 'Layers of flavor.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Beef', 'Italian'],
    preparationTime: Duration(minutes: 30),
    cookingTime: Duration(minutes: 60),
  ),
  CatigoryDetailClass(
    id: '18',
    catigory: "c3",
    image: 'images/pasta4.jpeg',
    title: 'Penne Arrabbiata',
    ingredients: 'Penne, Tomato Sauce, Garlic, Red Chili Flakes, Olive Oil, Parmesan Cheese',
    size: Sizes.medium,
    extra: 'Extra Chili Flakes',
    price: '\$11.49',
    calories: 650,
    rating: 4.6,
    reviews: ['Spicy and tangy!', 'Perfectly al dente pasta.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Spicy', 'Italian'],
    preparationTime: Duration(minutes: 10),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '19',
    catigory: "c3",
    image: 'images/pasta5.jpeg',
    title: 'Seafood Pasta',
    ingredients: 'Linguine, Shrimp, Mussels, Clams, Garlic, White Wine, Tomato Sauce, Parsley',
    size: Sizes.large,
    extra: 'Extra Shrimp',
    price: '\$16.99',
    calories: 750,
    rating: 4.8,
    reviews: ['Fresh and flavorful seafood!', 'A great choice for seafood lovers.'],
    allergens: ['Gluten', 'Shellfish'],
    tags: ['Seafood', 'Italian'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 25),
  ),
  CatigoryDetailClass(
    id: '20',
    catigory: "c3",
    image: 'images/pasta6.jpeg',
    title: 'Vegetable Pasta',
    ingredients: 'Pasta, Mixed Vegetables (Bell Peppers, Zucchini, Tomatoes), Olive Oil, Garlic, Parmesan Cheese',
    size: Sizes.medium,
    extra: 'Extra Olive Oil',
    price: '\$10.99',
    calories: 550,
    rating: 4.5,
    reviews: ['Healthy and tasty!', 'A great vegetarian option.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Vegetarian', 'Healthy'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '21',
    catigory: "c3",
    image: 'images/pasta7.jpeg',
    title: 'Gnocchi with Brown Butter Sauce',
    ingredients: 'Gnocchi, Brown Butter, Sage, Parmesan Cheese, Garlic, Black Pepper',
    size: Sizes.medium,
    extra: 'Extra Sage',
    price: '\$12.49',
    calories: 700,
    rating: 4.7,
    reviews: ['Unique and delicious!', 'The brown butter sauce is amazing.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Italian', 'Unique'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '22',
    catigory: "c4",
    image: 'images/pizza1.jpeg',
    title: 'Margherita Pizza',
    ingredients: 'Tomato Sauce, Mozzarella Cheese, Fresh Basil, Olive Oil',
    size: Sizes.medium,
    extra: 'Extra Basil',
    price: '\$11.99',
    calories: 700,
    rating: 4.7,
    reviews: ['Simple and delicious!', 'Classic Italian flavor.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Classic', 'Vegetarian'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '23',
    catigory: "c4",
    image: 'images/pizza2.jpeg',
    title: 'Pepperoni Pizza',
    ingredients: 'Tomato Sauce, Mozzarella Cheese, Pepperoni, Olive Oil',
    size: Sizes.medium,
    extra: 'Extra Pepperoni',
    price: '\$12.49',
    calories: 800,
    rating: 4.8,
    reviews: ['Perfectly crispy pepperoni!', 'A favorite for meat lovers.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Meat', 'Classic'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '24',
    catigory: "c4",
    image: 'images/pizza3.jpeg',
    title: 'Veggie Pizza',
    ingredients: 'Tomato Sauce, Mozzarella Cheese, Bell Peppers, Mushrooms, Olives, Onions, Spinach',
    size: Sizes.medium,
    extra: 'Extra Veggies',
    price: '\$11.49',
    calories: 650,
    rating: 4.6,
    reviews: ['Fresh and tasty veggies!', 'Great for vegetarians.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Vegetarian', 'Healthy'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '25',
    catigory: "c4",
    image: 'images/pizza4.jpeg',
    title: 'BBQ Chicken Pizza',
    ingredients: 'BBQ Sauce, Mozzarella Cheese, Grilled Chicken, Red Onions, Cilantro',
    size: Sizes.medium,
    extra: 'Extra BBQ Sauce',
    price: '\$13.49',
    calories: 750,
    rating: 4.7,
    reviews: ['Unique and flavorful!', 'BBQ sauce adds a great kick.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Chicken', 'BBQ'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '26',
    catigory: "c4",
    image: 'images/pizza5.jpeg',
    title: 'Meat Lovers Pizza',
    ingredients: 'Tomato Sauce, Mozzarella Cheese, Pepperoni, Sausage, Bacon, Ham',
    size: Sizes.large,
    extra: 'Extra Meat',
    price: '\$14.99',
    calories: 900,
    rating: 4.9,
    reviews: ['Loaded with meat!', 'A carnivore’s delight.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Meat', 'Hearty'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '27',
    catigory: "c4",
    image: 'images/pizza6.jpeg',
    title: 'White Pizza',
    ingredients: 'Olive Oil, Ricotta Cheese, Mozzarella Cheese, Garlic, Spinach, Parmesan Cheese',
    size: Sizes.medium,
    extra: 'Extra Garlic',
    price: '\$12.99',
    calories: 700,
    rating: 4.6,
    reviews: ['Creamy and flavorful!', 'A great alternative to traditional pizza.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Creamy', 'Vegetarian'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '28',
    catigory: "c4",
    image: 'images/pizza7.jpeg',
    title: 'Pesto Pizza',
    ingredients: 'Pesto Sauce, Mozzarella Cheese, Sun-Dried Tomatoes, Pine Nuts, Basil',
    size: Sizes.medium,
    extra: 'Extra Pesto',
    price: '\$13.99',
    calories: 650,
    rating: 4.8,
    reviews: ['Fresh and aromatic!', 'The pesto sauce is delicious.'],
    allergens: ['Gluten', 'Nuts (Pine Nuts)', 'Dairy'],
    tags: ['Pesto', 'Unique'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),

  CatigoryDetailClass(
    id: '29',
    catigory: "c5",
    image: 'images/fish1.jpeg',
    title: 'Grilled Salmon',
    ingredients: 'Salmon, Olive Oil, Lemon, Garlic, Dill, Salt, Pepper',
    size: Sizes.medium,
    extra: 'Extra Lemon Wedges',
    price: '\$18.99',
    calories: 400,
    rating: 4.8,
    reviews: ['Perfectly grilled!', 'The lemon adds a nice touch.'],
    allergens: ['Fish'],
    tags: ['Salmon', 'Healthy'],
    preparationTime: Duration(minutes: 10),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '30',
    catigory: "c5",
    image: 'images/fish2.jpeg',
    title: 'Baked Cod',
    ingredients: 'Cod, Breadcrumbs, Butter, Garlic, Lemon, Parsley, Salt, Pepper',
    size: Sizes.medium,
    extra: 'Extra Parsley',
    price: '\$17.49',
    calories: 350,
    rating: 4.7,
    reviews: ['Light and flaky!', 'The breadcrumbs add a nice crunch.'],
    allergens: ['Fish', 'Gluten'],
    tags: ['Cod', 'Baked'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '31',
    catigory: "c5",
    image: 'images/fish3.jpeg',
    title: 'Fish Tacos',
    ingredients: 'White Fish, Tortillas, Cabbage, Avocado, Lime, Cilantro, Salsa',
    size: Sizes.medium,
    extra: 'Extra Salsa',
    price: '\$14.99',
    calories: 600,
    rating: 4.6,
    reviews: ['Fresh and zesty!', 'Great combination of flavors.'],
    allergens: ['Fish', 'Gluten'],
    tags: ['Tacos', 'Mexican'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '32',
    catigory: "c5",
    image: 'images/fish4.jpeg',
    title: 'Fish and Chips',
    ingredients: 'White Fish, Potatoes, Flour, Beer, Baking Powder, Salt, Pepper',
    size: Sizes.large,
    extra: 'Extra Tartare Sauce',
    price: '\$15.99',
    calories: 800,
    rating: 4.8,
    reviews: ['Crispy and delicious!', 'A classic favorite.'],
    allergens: ['Fish', 'Gluten'],
    tags: ['Fried', 'British'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 25),
  ),
  CatigoryDetailClass(
    id: '33',
    catigory: "c5",
    image: 'images/fish5.jpeg',
    title: 'Spicy Fish Curry',
    ingredients: 'Fish, Coconut Milk, Tomatoes, Onions, Garlic, Ginger, Spices',
    size: Sizes.large,
    extra: 'Extra Rice',
    price: '\$16.49',
    calories: 700,
    rating: 4.7,
    reviews: ['Flavorful and spicy!', 'A great curry dish.'],
    allergens: ['Fish', 'Coconut'],
    tags: ['Curry', 'Spicy'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 30),
  ),
  CatigoryDetailClass(
    id: '34',
    catigory: "c5",
    image: 'images/fish6.jpeg',
    title: 'Teriyaki Swordfish',
    ingredients: 'Swordfish, Teriyaki Sauce, Garlic, Ginger, Sesame Seeds, Green Onions',
    size: Sizes.medium,
    extra: 'Extra Teriyaki Sauce',
    price: '\$19.99',
    calories: 450,
    rating: 4.8,
    reviews: ['Sweet and savory!', 'The teriyaki sauce is delicious.'],
    allergens: ['Fish', 'Soy'],
    tags: ['Swordfish', 'Japanese'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '35',
    catigory: "c5",
    image: 'images/fish7.jpeg',
    title: 'Fish Pie',
    ingredients: 'White Fish, Potatoes, Leeks, Cream, Cheese, Butter, Flour',
    size: Sizes.large,
    extra: 'Extra Cheese',
    price: '\$17.99',
    calories: 800,
    rating: 4.9,
    reviews: ['Rich and comforting!', 'A delicious pie.'],
    allergens: ['Fish', 'Dairy', 'Gluten'],
    tags: ['Pie', 'Comfort Food'],
    preparationTime: Duration(minutes: 30),
    cookingTime: Duration(minutes: 45),
  ),

  
  CatigoryDetailClass(
    id: '36',
    catigory: "c6",
    image: 'images/korean1.jpeg',
    title: 'Bibimbap',
    ingredients: 'Rice, Mixed Vegetables (Carrots, Spinach, Bean Sprouts), Beef, Egg, Gochujang (Korean Chili Paste), Sesame Oil',
    size: Sizes.large,
    extra: 'Extra Gochujang',
    price: '\$14.99',
    calories: 650,
    rating: 4.8,
    reviews: ['A vibrant and nutritious meal!', 'The gochujang adds perfect spice.'],
    allergens: ['Sesame'],
    tags: ['Korean', 'Vegetarian Option'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '37',
    catigory: "c6",
    image: 'images/korean2.jpeg',
    title: 'Kimchi Jjigae',
    ingredients: 'Kimchi, Pork, Tofu, Onion, Garlic, Korean Chili Flakes, Soy Sauce, Green Onion',
    size: Sizes.large,
    extra: 'Extra Kimchi',
    price: '\$13.49',
    calories: 700,
    rating: 4.7,
    reviews: ['Spicy and comforting!', 'The pork and kimchi blend perfectly.'],
    allergens: ['Soy'],
    tags: ['Korean', 'Spicy'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 30),
  ),
  CatigoryDetailClass(
    id: '38',
    catigory: "c6",
    image: 'images/korean3.jpeg',
    title: 'Bulgogi',
    ingredients: 'Marinated Beef, Soy Sauce, Sugar, Sesame Oil, Garlic, Green Onion, Pear Juice',
    size: Sizes.medium,
    extra: 'Extra Rice',
    price: '\$16.99',
    calories: 800,
    rating: 4.9,
    reviews: ['Tender and flavorful!', 'The marinade is fantastic.'],
    allergens: ['Soy'],
    tags: ['Korean', 'Grilled'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 20),
  ),
  
  // Chinese Dishes
  CatigoryDetailClass(
    id: '39',
    catigory: "c6",
    image: 'images/korean4.jpeg',
    title: 'Kung Pao Chicken',
    ingredients: 'Chicken, Peanuts, Bell Peppers, Dried Chili Peppers, Garlic, Ginger, Soy Sauce, Vinegar',
    size: Sizes.medium,
    extra: 'Extra Peanuts',
    price: '\$14.49',
    calories: 600,
    rating: 4.8,
    reviews: ['A perfect balance of sweet and spicy!', 'The peanuts add great crunch.'],
    allergens: ['Peanuts', 'Soy'],
    tags: ['Chinese', 'Spicy'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '40',
    catigory: "c6",
    image: 'images/korean5.jpeg',
    title: 'Mapo Tofu',
    ingredients: 'Tofu, Ground Pork, Doubanjiang (Bean Paste), Soy Sauce, Garlic, Ginger, Green Onion, Sichuan Peppercorns',
    size: Sizes.medium,
    extra: 'Extra Spice',
    price: '\$13.99',
    calories: 500,
    rating: 4.7,
    reviews: ['Rich and spicy!', 'The tofu is perfectly cooked.'],
    allergens: ['Soy'],
    tags: ['Chinese', 'Spicy', 'Vegetarian Option'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 20),
  ),
  CatigoryDetailClass(
    id: '41',
    catigory: "c6",
    image: 'images/korean6.jpeg',
    title: 'Dumplings',
    ingredients: 'Dumpling Wrappers, Ground Pork, Cabbage, Green Onion, Garlic, Soy Sauce, Ginger',
    size: Sizes.medium,
    extra: 'Extra Soy Sauce',
    price: '\$10.99',
    calories: 400,
    rating: 4.6,
    reviews: ['Delicious and savory!', 'Perfectly steamed dumplings.'],
    allergens: ['Gluten', 'Soy'],
    tags: ['Chinese', 'Appetizer'],
    preparationTime: Duration(minutes: 30),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '42',
    catigory: "c6",
    image: 'images/korean7.jpeg',
    title: 'Beef and Broccoli',
    ingredients: 'Beef, Broccoli, Soy Sauce, Garlic, Ginger, Oyster Sauce, Brown Sugar',
    size: Sizes.medium,
    extra: 'Extra Beef',
    price: '\$15.99',
    calories: 550,
    rating: 4.8,
    reviews: ['Tender beef with crunchy broccoli!', 'The sauce is full of flavor.'],
    allergens: ['Soy'],
    tags: ['Chinese', 'Healthy'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),

  CatigoryDetailClass(
    id: '43',
    catigory: "c7",
    image: 'images/meels1.jpeg',
    title: 'Grilled Chicken Salad',
    ingredients: 'Grilled Chicken, Mixed Greens, Cherry Tomatoes, Cucumber, Red Onion, Avocado, Olive Oil, Lemon Juice',
    size: Sizes.medium,
    extra: 'Extra Avocado',
    price: '\$12.99',
    calories: 400,
    rating: 4.7,
    reviews: ['Fresh and light!', 'Great for a healthy lunch.'],
    allergens: ['None'],
    tags: ['Salad', 'Healthy'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '44',
    catigory: "c7",
    image: 'images/meels2.jpeg',
    title: 'Spaghetti Bolognese',
    ingredients: 'Spaghetti, Ground Beef, Tomato Sauce, Onion, Garlic, Carrots, Celery, Red Wine, Parmesan Cheese',
    size: Sizes.large,
    extra: 'Extra Parmesan Cheese',
    price: '\$14.99',
    calories: 750,
    rating: 4.8,
    reviews: ['Rich and hearty!', 'The sauce is amazing.'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Pasta', 'Italian'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 30),
  ),
  CatigoryDetailClass(
    id: '45',
    catigory: "c7",
    image: 'images/meels3.jpeg',
    title: 'Chicken Curry',
    ingredients: 'Chicken, Onion, Garlic, Ginger, Curry Powder, Coconut Milk, Tomatoes, Cilantro',
    size: Sizes.large,
    extra: 'Extra Rice',
    price: '\$15.49',
    calories: 700,
    rating: 4.9,
    reviews: ['Spicy and flavorful!', 'Perfect with rice.'],
    allergens: ['Coconut'],
    tags: ['Curry', 'Spicy'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 30),
  ),
  CatigoryDetailClass(
    id: '46',
    catigory: "c7",
    image: 'images/meels4.jpeg',
    title: 'Beef Stir-Fry',
    ingredients: 'Beef, Bell Peppers, Broccoli, Carrots, Soy Sauce, Garlic, Ginger, Sesame Oil',
    size: Sizes.medium,
    extra: 'Extra Beef',
    price: '\$13.99',
    calories: 500,
    rating: 4.6,
    reviews: ['Quick and delicious!', 'The beef is tender and flavorful.'],
    allergens: ['Soy', 'Sesame'],
    tags: ['Stir-Fry', 'Chinese'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '47',
    catigory: "c7",
    image: 'images/meels5.jpeg',
    title: 'Veggie Burger',
    ingredients: 'Veggie Patty, Whole Wheat Bun, Lettuce, Tomato, Onion, Pickles, Ketchup, Mustard',
    size: Sizes.medium,
    extra: 'Extra Pickles',
    price: '\$11.99',
    calories: 450,
    rating: 4.7,
    reviews: ['Tasty and satisfying!', 'Great for a meatless meal.'],
    allergens: ['Gluten'],
    tags: ['Burger', 'Vegetarian'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '48',
    catigory: "c7",
    image: 'images/meels6.jpeg',
    title: 'Tacos',
    ingredients: 'Taco Shells, Ground Beef, Lettuce, Tomato, Cheddar Cheese, Sour Cream, Salsa',
    size: Sizes.large,
    extra: 'Extra Salsa',
    price: '\$12.49',
    calories: 600,
    rating: 4.8,
    reviews: ['Flavorful and fun to eat!', 'The salsa adds a nice kick.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Mexican', 'Tacos'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '49',
    catigory: "c7",
    image: 'images/meels7.jpeg',
    title: 'Lentil Soup',
    ingredients: 'Lentils, Carrots, Celery, Onion, Garlic, Tomatoes, Vegetable Broth, Thyme, Bay Leaf',
    size: Sizes.large,
    extra: 'Extra Bread',
    price: '\$10.99',
    calories: 350,
    rating: 4.7,
    reviews: ['Hearty and comforting!', 'Perfect for a chilly day.'],
    allergens: ['None'],
    tags: ['Soup', 'Vegetarian'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 45),
  ),

  CatigoryDetailClass(
    id: '50',
    catigory: "c8",
    image: 'images/crepe1.jpeg',
    title: 'Crepe Suzette',
    ingredients: 'Crepes, Orange Juice, Zest, Grand Marnier, Butter, Sugar, Lemon Juice',
    size: Sizes.medium,
    extra: 'Extra Sauce',
    price: '\$12.99',
    calories: 400,
    rating: 4.8,
    reviews: ['Delicately sweet with a citrusy twist!', 'A classic French favorite.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['French', 'Sweet'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '51',
    catigory: "c8",
    image: 'images/crepe6.jpeg',
    title: 'Banana Nutella Crepe',
    ingredients: 'Crepes, Nutella, Bananas, Whipped Cream, Powdered Sugar',
    size: Sizes.medium,
    extra: 'Extra Nutella',
    price: '\$11.99',
    calories: 500,
    rating: 4.9,
    reviews: ['Rich and indulgent!', 'Perfect for dessert.'],
    allergens: ['Dairy', 'Gluten', 'Nut'],
    tags: ['Sweet', 'Dessert'],
    preparationTime: Duration(minutes: 10),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '52',
    catigory: "c8",
    image: 'images/crepe2.jpeg',
    title: 'Savory Crepe',
    ingredients: 'Crepes, Ham, Cheese, Spinach, Mushrooms, Béchamel Sauce',
    size: Sizes.medium,
    extra: 'Extra Cheese',
    price: '\$13.49',
    calories: 600,
    rating: 4.7,
    reviews: ['Savory and satisfying!', 'Great for a light lunch.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Savory', 'Lunch'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '53',
    catigory: "c8",
    image: 'images/crepe3.jpeg',
    title: 'Berry Crepe',
    ingredients: 'Crepes, Mixed Berries (Strawberries, Blueberries, Raspberries), Yogurt, Honey',
    size: Sizes.medium,
    extra: 'Extra Honey',
    price: '\$12.49',
    calories: 350,
    rating: 4.8,
    reviews: ['Fresh and fruity!', 'A light and delicious treat.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Sweet', 'Healthy'],
    preparationTime: Duration(minutes: 10),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '55',
    catigory: "c8",
    image: 'images/crepe4.jpeg',
    title: 'Crepe Monte Carlo',
    ingredients: 'Crepes, Ham, Swiss Cheese, Turkey, Dijon Mustard',
    size: Sizes.medium,
    extra: 'Extra Ham',
    price: '\$14.99',
    calories: 650,
    rating: 4.7,
    reviews: ['A savory twist on the classic crepe!', 'Deliciously cheesy.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Savory', 'French'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '56',
    catigory: "c8",
    image: 'images/crepe5.jpeg',
    title: 'Crepe with Maple Syrup',
    ingredients: 'Crepes, Maple Syrup, Butter, Powdered Sugar',
    size: Sizes.medium,
    extra: 'Extra Maple Syrup',
    price: '\$11.49',
    calories: 450,
    rating: 4.6,
    reviews: ['Simple and classic!', 'The syrup is delightful.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Sweet', 'Breakfast'],
    preparationTime: Duration(minutes: 10),
    cookingTime: Duration(minutes: 10),
  ),
  CatigoryDetailClass(
    id: '57',
    catigory: "c8",
    image: 'images/crepe7.jpeg',
    title: 'Mango Crepe',
    ingredients: 'Crepes, Fresh Mango, Coconut Cream, Mint Leaves',
    size: Sizes.medium,
    extra: 'Extra Coconut Cream',
    price: '\$13.99',
    calories: 400,
    rating: 4.8,
    reviews: ['Tropical and refreshing!', 'Mango and coconut make a great combo.'],
    allergens: ['Dairy', 'Gluten', 'Coconut'],
    tags: ['Sweet', 'Tropical'],
    preparationTime: Duration(minutes: 10),
    cookingTime: Duration(minutes: 10),
  ),

  CatigoryDetailClass(
    id: '58',
    catigory: "c9",
    image: 'images/sweet2.jpeg',
    title: 'Chocolate Cake',
    ingredients: 'Flour, Cocoa Powder, Sugar, Eggs, Butter, Baking Powder, Vanilla Extract, Milk',
    size: Sizes.large,
    extra: 'Extra Chocolate Sauce',
    price: '\$6.99',
    calories: 450,
    rating: 4.9,
    reviews: ['Rich and decadent!', 'A chocolate lover\'s dream.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Cake', 'Dessert'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 40),
  ),
  CatigoryDetailClass(
    id: '59',
    catigory: "c9",
    image: 'images/sweet5.jpeg',
    title: 'Cheesecake',
    ingredients: 'Cream Cheese, Sugar, Eggs, Graham Cracker Crust, Butter, Vanilla Extract',
    size: Sizes.large,
    extra: 'Extra Berry Compote',
    price: '\$7.49',
    calories: 500,
    rating: 4.8,
    reviews: ['Smooth and creamy!', 'The berry compote adds a nice touch.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Dessert', 'Cheese'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 60),
  ),
  CatigoryDetailClass(
    id: '60',
    catigory: "c9",
    image: 'images/sweet4.jpeg',
    title: 'Apple Pie',
    ingredients: 'Apples, Sugar, Cinnamon, Nutmeg, Pie Crust, Butter',
    size: Sizes.large,
    extra: 'Extra Vanilla Ice Cream',
    price: '\$5.99',
    calories: 400,
    rating: 4.7,
    reviews: ['Classic and comforting!', 'The ice cream pairing is perfect.'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Pie', 'Dessert'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 50),
  ),
  CatigoryDetailClass(
    id: '61',
    catigory: "c9",
    image: 'images/sweet1.jpeg',
    title: 'Tiramisu',
    ingredients: 'Mascarpone Cheese, Coffee, Ladyfingers, Eggs, Sugar, Cocoa Powder',
    size: Sizes.medium,
    extra: 'Extra Cocoa Powder',
    price: '\$6.49',
    calories: 350,
    rating: 4.8,
    reviews: ['Deliciously rich and creamy!', 'A perfect end to any meal.'],
    allergens: ['Dairy', 'Eggs', 'Gluten'],
    tags: ['Italian', 'Dessert'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 0), // No baking, just chilling
  ),
  CatigoryDetailClass(
    id: '62',
    catigory: "c9",
    image: 'images/sweet3.jpeg',
    title: 'Macaron',
    ingredients: 'Almond Flour, Sugar, Egg Whites, Butter, Filling (e.g., Ganache, Jam)',
    size: Sizes.small,
    extra: 'Extra Filling',
    price: '\$2.49 per piece',
    calories: 100,
    rating: 4.7,
    reviews: ['Light and airy with a burst of flavor!', 'Perfectly sweet.'],
    allergens: ['Nuts', 'Dairy'],
    tags: ['French', 'Sweet'],
    preparationTime: Duration(minutes: 30),
    cookingTime: Duration(minutes: 15),
  ),
  CatigoryDetailClass(
    id: '66',
    catigory: "c9",
    image: 'images/sweet6.jpeg',
    title: 'Crème Brûlée',
    ingredients: 'Cream, Egg Yolks, Sugar, Vanilla Bean, Brown Sugar',
    size: Sizes.medium,
    extra: 'Extra Caramelized Sugar',
    price: '\$7.99',
    calories: 400,
    rating: 4.9,
    reviews: ['Silky smooth with a perfect caramelized top!', 'A classic French dessert.'],
    allergens: ['Dairy', 'Eggs'],
    tags: ['French', 'Dessert'],
    preparationTime: Duration(minutes: 15),
    cookingTime: Duration(minutes: 45),
  ),
  CatigoryDetailClass(
    id: '67',
    catigory: "c9",
    image: 'images/sweet7.jpeg',
    title: 'Doughnuts',
    ingredients: 'Flour, Sugar, Eggs, Milk, Butter, Yeast, Nutmeg, Glaze',
    size: Sizes.medium,
    extra: 'Extra Glaze',
    price: '\$4.99 for 3',
    calories: 300,
    rating: 4.6,
    reviews: ['Sweet and fluffy!', 'The glaze is irresistible.'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    tags: ['Sweet', 'Breakfast'],
    preparationTime: Duration(minutes: 20),
    cookingTime: Duration(minutes: 20),
  ),

  CatigoryDetailClass(
    id: '68',
    catigory: "c10",
    image: 'images/cold1.jpeg',
    title: 'Iced Coffee',
    ingredients: 'Coffee, Ice, Milk, Sugar, Vanilla Syrup',
    size: Sizes.medium,
    extra: 'Extra Vanilla Syrup',
    price: '\$4.99',
    calories: 120,
    rating: 4.7,
    reviews: ['Refreshing and strong!', 'Perfect for a hot day.'],
    allergens: ['Dairy'],
    tags: ['Coffee', 'Cold'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '69',
    catigory: "c10",
    image: 'images/cold2.jpeg',
    title: 'Mango Smoothie',
    ingredients: 'Mango, Yogurt, Honey, Ice, Lime Juice',
    size: Sizes.large,
    extra: 'Extra Mango',
    price: '\$5.49',
    calories: 300,
    rating: 4.8,
    reviews: ['Tropical and creamy!', 'A delicious blend of flavors.'],
    allergens: ['Dairy'],
    tags: ['Smoothie', 'Cold'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '70',
    catigory: "c10",
    image: 'images/cold3.jpeg',
    title: 'Lemonade',
    ingredients: 'Lemon Juice, Water, Sugar, Ice, Mint Leaves',
    size: Sizes.medium,
    extra: 'Extra Mint',
    price: '\$3.99',
    calories: 150,
    rating: 4.6,
    reviews: ['Sweet and tangy!', 'A classic summer drink.'],
    allergens: ['None'],
    tags: ['Juice', 'Cold'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '71',
    catigory: "c10",
    image: 'images/cold4.jpeg',
    title: 'Iced Tea',
    ingredients: 'Black Tea, Ice, Lemon, Sugar',
    size: Sizes.medium,
    extra: 'Extra Lemon',
    price: '\$3.49',
    calories: 80,
    rating: 4.5,
    reviews: ['Light and refreshing!', 'Perfectly brewed.'],
    allergens: ['None'],
    tags: ['Tea', 'Cold'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '72',
    catigory: "c10",
    image: 'images/cold5.jpeg',
    title: 'Strawberry Milkshake',
    ingredients: 'Strawberries, Milk, Ice Cream, Sugar, Whipped Cream',
    size: Sizes.large,
    extra: 'Extra Whipped Cream',
    price: '\$6.49',
    calories: 500,
    rating: 4.9,
    reviews: ['Sweet and creamy!', 'The whipped cream makes it perfect.'],
    allergens: ['Dairy'],
    tags: ['Milkshake', 'Cold'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '73',
    catigory: "c10",
    image: 'images/cold6.jpeg',
    title: 'Cold Brew Coffee',
    ingredients: 'Cold Brew Coffee, Ice, Milk, Simple Syrup',
    size: Sizes.medium,
    extra: 'Extra Simple Syrup',
    price: '\$5.99',
    calories: 80,
    rating: 4.8,
    reviews: ['Smooth and less acidic!', 'A great coffee alternative.'],
    allergens: ['Dairy'],
    tags: ['Coffee', 'Cold'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '74',
    catigory: "c10",
    image: 'images/cold7.jpeg',
    title: 'Fruit Punch',
    ingredients: 'Orange Juice, Pineapple Juice, Lemon Juice, Lime Juice, Mixed Fruit',
    size: Sizes.large,
    extra: 'Extra Fruit',
    price: '\$4.49',
    calories: 200,
    rating: 4.7,
    reviews: ['Fruity and refreshing!', 'Great for a party.'],
    allergens: ['None'],
    tags: ['Juice', 'Cold'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  
  CatigoryDetailClass(
    id: '75',
    catigory: "c11",
    image: 'images/hot1.jpeg',
    title: 'Latte',
    ingredients: 'Espresso, Steamed Milk, Foam',
    size: Sizes.medium,
    extra: 'Extra Shot of Espresso',
    price: '\$4.99',
    calories: 150,
    rating: 4.8,
    reviews: ['Smooth and creamy!', 'A great way to start the day.'],
    allergens: ['Dairy'],
    tags: ['Coffee', 'Hot'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '76',
    catigory: "c11",
    image: 'images/hot2.jpg',
    title: 'Cappuccino',
    ingredients: 'Espresso, Steamed Milk, Milk Foam',
    size: Sizes.medium,
    extra: 'Extra Foam',
    price: '\$4.79',
    calories: 120,
    rating: 4.7,
    reviews: ['Perfect balance of espresso and milk!', 'Love the frothy top.'],
    allergens: ['Dairy'],
    tags: ['Coffee', 'Hot'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '77',
    catigory: "c11",
    image: 'images/hot3.jpeg',
    title: 'Tea',
    ingredients: 'Tea Leaves, Hot Water, Optional Milk, Sugar',
    size: Sizes.medium,
    extra: 'Extra Sugar',
    price: '\$3.49',
    calories: 0,
    rating: 4.5,
    reviews: ['Soothing and relaxing!', 'Great for any time of day.'],
    allergens: ['None'],
    tags: ['Tea', 'Hot'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '78',
    catigory: "c11",
    image: 'images/hot4.jpeg',
    title: 'Hot Chocolate',
    ingredients: 'Milk, Cocoa Powder, Sugar, Whipped Cream',
    size: Sizes.medium,
    extra: 'Extra Whipped Cream',
    price: '\$4.99',
    calories: 250,
    rating: 4.9,
    reviews: ['Rich and chocolatey!', 'A perfect winter treat.'],
    allergens: ['Dairy'],
    tags: ['Chocolate', 'Hot'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '79',
    catigory: "c11",
    image: 'images/hot5.jpeg',
    title: 'English Breakfast Tea',
    ingredients: 'Black Tea Leaves, Hot Water, Optional Milk, Sugar',
    size: Sizes.medium,
    extra: 'Extra Milk',
    price: '\$3.29',
    calories: 0,
    rating: 4.6,
    reviews: ['Strong and full-bodied!', 'A great start to the day.'],
    allergens: ['None'],
    tags: ['Tea', 'Hot'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '80',
    catigory: "c11",
    image: 'images/hot6.jpeg',
    title: 'Americano',
    ingredients: 'Espresso, Hot Water',
    size: Sizes.medium,
    extra: 'Extra Shot of Espresso',
    price: '\$4.29',
    calories: 50,
    rating: 4.7,
    reviews: ['Bold and strong!', 'Perfect for a coffee kick.'],
    allergens: ['None'],
    tags: ['Coffee', 'Hot'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),
  CatigoryDetailClass(
    id: '81',
    catigory: "c11",
    image: 'images/hot7.jpeg',
    title: 'Chai Latte',
    ingredients: 'Chai Tea, Steamed Milk, Spices',
    size: Sizes.medium,
    extra: 'Extra Spices',
    price: '\$5.49',
    calories: 180,
    rating: 4.8,
    reviews: ['Spicy and comforting!', 'A great twist on traditional tea.'],
    allergens: ['Dairy'],
    tags: ['Tea', 'Hot'],
    preparationTime: Duration(minutes: 5),
    cookingTime: Duration(minutes: 0),
  ),

];